 <?php if ($this->pageCount): ?>
     <div class="pagination-centered">
         <ul class="pagination">
             <!-- Previous page link -->
             <?php if (isset($this->previous)): ?>
                 <li class="arrow">
                     <a href="<?php echo $this->url($this->route, array('page' => $page)); ?>">
                         &laquo;
                     </a>
                 </li>
             <?php else: ?>
                 <li class="arrow unavailable">
                     <a href="">
                         &laquo;
                     </a>
                 </li>
             <?php endif; ?>

             <!-- Numbered page links -->
             <?php foreach ($this->pagesInRange as $page): ?>
                 <?php if ($page != $this->current): ?>
                     <li>
                         <a href="<?php echo $this->url($this->route, array('page' => $page));?>">
                             <?php echo $page; ?>
                         </a>
                     </li>
                 <?php else: ?>
                     <li class="current">
                         <a href=""><?php echo $page; ?></a>
                     </li>
                 <?php endif; ?>
             <?php endforeach; ?>

             <!-- Next page link -->
             <?php if (isset($this->next)): ?>
                 <li class="arrow">
                     <a href="<?php echo $this->url($this->route, array('page' => $page)); ?>">
                         &raquo;
                     </a>
                 </li>
             <?php else: ?>
                 <li class="arrow unavailable">
                     <a href="#">
                         &raquo;
                     </a>
                 </li>
             <?php endif; ?>
         </ul>
     </div>
 <?php endif; ?>