<?php
// module/Application/view/application/power/add.phtml:

$title = 'Power Administration';
$this->headTitle($title);
?>
<div class="large-10 columns">
    <h4><?php echo $this->translate('Power Form') ?></h4>    
    <?php 
    $this->form->prepare();
    echo $this->form()->openTag($this->form);
    ?>
    <div class="row">
        <div class="small-7">
            <div class="small-3 columns">
                <label for="right-label" class="right inline"><?php echo $this->translate('Role') ?></label>
            </div>
            <div class="small-9 columns">
                <?php echo $this->formRow($this->form->get('roleid')) ?>
            </div>
        </div>
    </div>
    <!--
    <div class="row">
        <div class="small-7">
            <div class="small-3 columns">
                <label for="right-label" class="right inline"><?php echo $this->translate('Module') ?></label>
            </div>
            <div class="small-9 columns">
                <?php echo $this->formRow($this->form->get('module')) ?>
            </div>
        </div>
    </div>
    
    <div class="row">
        <div class="small-7">
            <div class="small-3 columns">
                <label for="right-label" class="right inline"><?php echo $this->translate('Controller') ?></label>
            </div>
            <div class="small-9 columns">
                <?php echo $this->formRow($this->form->get('controller')) ?>
            </div>
        </div>
    </div>
    -->
    <div class="row">
        <div class="small-7">
            <div class="small-3 columns">
                <label for="right-label" class="right inline"><?php echo $this->translate('Action') ?></label>
            </div>
            <div class="small-9 columns">
                <?php echo $this->formRow($this->form->get('action')) ?>
            </div>
        </div>
    </div>
    
    <div class="row">
        <div class="small-7">
            <div class="small-3 columns"></div>
            <div class="small-9 columns">
                <?php echo $this->formElement($this->form->get('submit')) ?>
            </div>
        </div>
    </div>
    
    <?php 
    echo $this->formHidden($this->form->get('csrf'));
    echo $this->form()->closeTag();
    ?>
</div>