<?php 
if($this->loginSuccess) {
    echo 'Hallo, '.$this->userLoggedIn.'!';
} else {
    if($this->loginError)
        echo 'Die eingegebenen Daten sind ungültig.';
    
    $this->form->prepare();
    echo $this->form()->openTag($this->form);
    echo '<h2 class="form-signin-heading">Please sign in</h2>';
    echo $this->formRow($this->form->get('username'));
    echo $this->formRow($this->form->get('password'));
//     echo $this->formHidden($this->form->get('csrf'));
    echo $this->formElement($this->form->get('submit'));
    echo $this->form()->closeTag();
}
