<div class="large-10 columns">
    <h4 class="error"><i class="fa fa-exclamation-triangle"></i> <?php echo $this->translate('An error occurred') ?></h4>
    
    <p>
        <?php echo $this->message ?>
    </p>
    
    <?php if (isset($this->display_exceptions) && $this->display_exceptions): ?>
    
    <?php if(isset($this->exception) && $this->exception instanceof Exception): ?>
    <hr/>
    <h4><?php echo $this->translate('Additional information') ?>:</h4>
    <h5><?php echo get_class($this->exception); ?></h5>
    <dl>
        <dt><?php echo $this->translate('File') ?>:</dt>
        <dd>
            <pre class="prettyprint linenums"><?php echo $this->exception->getFile() ?>:<?php echo $this->exception->getLine() ?></pre>
        </dd>
        <dt><?php echo $this->translate('Message') ?>:</dt>
        <dd>
            <pre class="prettyprint linenums"><?php echo $this->escapeHtml($this->exception->getMessage()) ?></pre>
        </dd>
        <dt><?php echo $this->translate('Stack trace') ?>:</dt>
        <dd>
            <pre class="prettyprint linenums"><?php echo $this->escapeHtml($this->exception->getTraceAsString()) ?></pre>
        </dd>
    </dl>
    <?php
        $e = $this->exception->getPrevious();
        if ($e) :
    ?>
    <hr/>
    <h4><?php echo $this->translate('Previous exceptions') ?>:</h4>
    <ul class="unstyled">
        <?php while($e) : ?>
        <li>
            <h3><?php echo get_class($e); ?></h3>
            <dl>
                <dt><?php echo $this->translate('File') ?>:</dt>
                <dd>
                    <pre class="prettyprint linenums"><?php echo $e->getFile() ?>:<?php echo $e->getLine() ?></pre>
                </dd>
                <dt><?php echo $this->translate('Message') ?>:</dt>
                <dd>
                    <pre class="prettyprint linenums"><?php echo $this->escapeHtml($e->getMessage()) ?></pre>
                </dd>
                <dt><?php echo $this->translate('Stack trace') ?>:</dt>
                <dd>
                    <pre class="prettyprint linenums"><?php echo $this->escapeHtml($e->getTraceAsString()) ?></pre>
                </dd>
            </dl>
        </li>
        <?php
            $e = $e->getPrevious();
            endwhile;
        ?>
    </ul>
    <?php endif; ?>
    
    <?php else: ?>
    
    <h4><?php echo $this->translate('No Exception available') ?></h4>
    
    <?php endif ?>
    
    <?php endif ?>
</div>
