<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Roombooking\Module'                        => __DIR__ . '/Module.php',
    'Roombooking\Controller\RoombookingController' => __DIR__ . '/src/Roombooking/Controller/RoombookingController.php',
    'RoombookingTest\Framework\TestCase'        => __DIR__ . '/tests/Roombooking/Framework/TestCase.php',
    'RoombookingTest\SampleTest'                => __DIR__ . '/tests/Roombooking/SampleTest.php',
);
