<?php echo $this->doctype(); ?>
<html class="no-js" lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<?php echo $this->headTitle('Quality and Usability Lab '. $this->translate('Room Booking System'))->setSeparator(' - ')->setAutoEscape(false) ?>

<!-- Stylesheet -->
<?php echo $this
    /*
     * Stylesheet order will be inverse in the markup!
     */
    ->headLink()
    
    // Roombooking Tool specific styles
    ->prependStylesheet($this->basePath() . '/css/roombooking.css')
    
    // Calendar Specific Styles
    ->prependStylesheet($this->basePath() . '/js/fullcalendar/fullcalendar.print.css')
    ->prependStylesheet($this->basePath() . '/js/fullcalendar/fullcalendar.css')
    
    // General Styles
    ->prependStylesheet($this->basePath() . '/css/foundation.css')
    ->prependStylesheet($this->basePath() . '/css/font-awesome.css')
?>

<!-- Head Scripts (Application specific scripts will be loaded at the end.) -->
<?php echo $this->headScript()
    ->prependFile($this->basePath() . '/js/vendor/modernizr.js')
?>
</head>
<body>

    <div class="row" id="titlerow">
        <div class="large-2 columns">
            <a href="<?php echo $this->url('home') ?>">
                <img src="<?php echo $this->basePath() ?>/img/TU-Berlin-Logo.svg" id="tulogo" title="<?php echo $this->translate('Home') ?>" alt="<?php echo $this->translate('Logo of the TU Berlin') ?>">
            </a>
        </div>
        
        <div class="large-10 columns">
            <h1>
                <?php echo $this->translate('Room Booking System') ?> <small>Quality and Usability Lab</small>
            </h1>
        </div>
    </div>

    <div class="row">
        <!-- Nav Sidebar -->
        <!-- FIXME This menus should be generated automatically! -->
        <div class="large-2 columns">
            <ul class="side-nav">
                <li><a href="#">Admin</a></li>
                <li><a href="#">Main App</a></li>
                <li><a href="#">Settings</a></li>
            </ul>
        </div>

        <!-- Main Content Section -->
        <?php echo $this->content; ?>
    </div>

    <footer class="row">
        <div class="large-12 columns">
            <hr>
            <p>
                <strong>Institut für Softwaretechnik und Theoretische Informatik,</strong><br>
                Quality and Usability Lab (2013 - <?php echo date('Y') ?>)
            </p>
        </div>
    </footer>
    
<!-- General JavaScript Components -->
<?php echo $this->inlineScript()
    /*
     * Script order will be inverse in the markup!
     */
    ->prependFile($this->basePath() . '/js/roombooking/roombooking.js')
    ->prependFile($this->basePath() . '/js/vendor/require.js')
?>
</body>
</html>
 