<?php echo $this->doctype(); ?>
<html class="no-js" lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<?php echo $this->headTitle('pjroombooking '. $this->translate('Room Booking System'))->setSeparator(' - ')->setAutoEscape(false) ?>

<script type="text/javascript">
    // Provide a global window object in order to store configuration for JavaScript components
    window.roombooking = {};
</script>

<!-- Stylesheet -->
<?php echo $this
    /*
     * Stylesheet order will be inverse in the markup!
     */
    ->headLink()
    
    // Roombooking Tool specific styles
    ->prependStylesheet($this->basePath() . '/css/roombooking.css')
    
    // General Styles
    ->prependStylesheet($this->basePath() . '/css/foundation.css')
    ->prependStylesheet($this->basePath() . '/css/font-awesome.css')
?>

<!-- Head Scripts (Application specific scripts will be loaded at the end.) -->
<?php echo $this->headScript()
    ->prependFile($this->basePath() . '/js/vendor/modernizr.js')
?>
</head>
<body>

    <div class="row" id="titlerow">
        <div class="large-2 columns">
            
            <a href="<?php echo $this->url('home') ?>">
                <img src="<?php echo $this->basePath() ?>/img/logo.svg" id="logo" title="<?php echo $this->translate('Home') ?>" alt="<?php echo $this->translate('Logo') ?>">
            </a>
            
        </div>
        
        <div class="large-10 columns">
            <h1>
                <?php echo $this->translate('Room Booking System') ?> <small><?php echo $this->translate('pjroombooking') ?></small>
            </h1>
        </div>
    </div>

    <div class="row">
        <!-- Nav Sidebar -->
        <div class="large-2 columns">
            <?php  if($this->userIdentity()) : ?>
            <ul class="side-nav">
                <?php //FIXME: use Zend Navigation
                    if($this->acl()->isAllowed($this->userIdentity(), 'show_user_details') OR $this->acl()->isAllowed($this->userIdentity(), 'show_power_list') OR $this->acl()->isAllowed($this->userIdentity(), 'show_resource_list') OR $this->acl()->isAllowed($this->userIdentity(), 'show_log')) :
                ?>
                <li>Administrative Area
                    <ul>
                        <?php if($this->acl()->isAllowed($this->userIdentity(), 'show_user_details')) : ?><li><a href="<?php echo $this->url('user'); ?>"><?php echo $this->translate('Users') ?></a></li><?php endif; ?>
                        <?php if($this->acl()->isAllowed($this->userIdentity(), 'show_power_list')) : ?><li><a href="<?php echo $this->url('power'); ?>"><?php echo $this->translate('Powers') ?></a></li><?php endif; ?>
                        <?php if($this->acl()->isAllowed($this->userIdentity(), 'show_resource_list')) : ?><li><a href="<?php echo $this->url('hierarchy'); ?>"><?php echo $this->translate('Resources') ?></a></li><?php endif; ?>
                        <?php if($this->acl()->isAllowed($this->userIdentity(), 'show_log')) : ?><li><a href="<?php echo $this->url('incidents'); ?>"><?php echo $this->translate('Log') ?></a></li><?php endif; ?>
                    </ul>
                </li>
                <li><hr></li>
                <?php endif; ?>
                <li>User Area
                    <ul>
                        <li><a href="<?php echo $this->url('home'); ?>"><?php echo $this->translate('Overview') ?></a></li>
                        <?php if($this->acl()->isAllowed($this->userIdentity(), 'add_own_appointment')) : ?><li><a href="<?php echo $this->url('booking/bookingEdit'); ?>"><?php echo $this->translate('Add Booking') ?></a></li><?php endif; ?>
                    </ul>
                </li>
                <li><hr></li>
                <li><a href="<?php echo $this->url('logout'); ?>"><?php echo $this->translate('Logout') ?></a></li>
            </ul>
            <?php endif; ?>
        </div>

        <!-- Main Content Section -->
        <?php echo $this->content; ?>
    </div>

    <footer class="row">
        <div class="large-12 columns">
            <hr>
            <p>
                <strong><?php echo $this->translate('pjroombooking') ?></strong><br>
                <?php echo $this->translate('pjroombooking') ?> (2013 - <?php echo date('Y') ?>)
            </p>
        </div>
    </footer>
    
<!-- General JavaScript Components -->
<?php echo $this->inlineScript()
    /*
     * Script order will be inverse in the markup!
     */
    ->prependFile($this->basePath() . '/js/roombooking/roombooking.js')
    ->prependFile($this->basePath() . '/js/vendor/require.js')
?>
</body>
</html>
 