<div class="large-10 columns">
	<h4><?php echo $this->translate('User Overview') ?></h4>
	
	<a href="<?php echo $this->url('user/refresh');?>" class="button synchronize-ldap-button right"><?php echo $this->translate('Synchronize with LDAP') ?></a>
	
	<?php if($users->count() === 0) : ?>
	<div data-alert class="alert-box">
        <?php echo $this->translate('No users in database.') ?> <a href="#" class="close">&times;</a>
    </div>
    <?php endif; ?>
    
	<!-- Table -->
	<table class="users">
		<thead>
			<tr>
				<th><?php echo $this->translate('Internal ID') ?></th>
				<th><?php echo $this->translate('LDAP UID') ?></th>
				<th><?php echo $this->translate('Username') ?></th>
				<th><?php echo $this->translate('First Name') ?></th>
				<th><?php echo $this->translate('Last Name') ?></th>
				<th><?php echo $this->translate('E-Mail') ?></th>
				<th><?php echo $this->translate('Role') ?></th>
			</tr>
		</thead>
		<tbody>
         <?php foreach ($users as $user) : ?>
         <tr class="user-record-row">
              <td><?php echo $this->escapeHtml($user->getId());?></td>
              <td><?php echo $this->escapeHtml($user->getLdapId());?></td>
              <td><?php echo $this->escapeHtml($user->getLoginName());?></td>
              <td><?php echo $this->escapeHtml($user->getFirstName());?></td>
              <td><?php echo $this->escapeHtml($user->getLastName());?></td>
              <td><?php echo $this->escapeHtml($user->getEmail());?></td>
              <td><select data-id="<?php echo $this->escapeHtml($user->getId()); ?>">
                  <?php foreach ($roles as $role) : ?>
                  <option value="<?php echo $role->getId(); ?>" <?php if($role->getId() == $user->getRole()) echo 'selected';?>><?php echo $this->escapeHtml($role->getName());?></option>
                  <?php endforeach; ?>
                  </select>
              </td>
         </tr>
         <?php endforeach; ?>
        </tbody>
	</table>
	
	<a href="<?php echo $this->url('user/refresh');?>" class="button synchronize-ldap-button right"><?php echo $this->translate('Synchronize with LDAP') ?></a>
</div>

<!-- User View Specific JavaScript Components -->
<?php $this->inlineScript()
    ->prependFile($this->basePath() . '/js/roombooking/users.js')
?>