<!-- Add/edit Specific CSS Components -->
<?php
    $this->headLink()->prependStylesheet($this->basePath() . '/js/jstree/dist/themes/default/style.css');
?> 

<div class="large-10 columns">
	<!-- Prepare the form -->
	<?php $form->prepare(); ?>
	<?php echo $this->form()->openTag($form); ?>
	
    <div class="row">
        <div class="name-field large-12 column">
    	   <h4><?php echo $this->translate('New Room Booking') ?></h4>
    	</div>
    </div>
    
    <div class="row">
    	<div class="name-field large-12 column">
    		<label>Booking Title <small>required</small>
    		  <?php echo $this->formRow($form->get('title'))?>
    		</label>
    		<small class="error">The title of the booking is required.</small>
    	</div>
	</div>
	
	<div class="row">
	   <div class="name-field medium-6 column">
	       links
	   </div>
	   
	   <div class="name-field medium-6 column">
	       <div id="resourcetree"></div>
	       <?php echo $this->formRow($form->get('resourceid'))?>
	   </div>
	</div>


<!-- Close the form -->
<?php echo $this->formHidden($this->form->get('csrf')); ?>
	<?php echo $this->form()->closeTag();?>
</div>

<!-- Add/edit Specific JavaScript Components -->
<?php $this->inlineScript()
    ->prependFile($this->basePath() . '/js/roombooking/edit.js')
?>