<!-- Add/edit Specific CSS Components -->
<?php
$this->headLink()->prependStylesheet(
        $this->basePath() . '/js/jstree/dist/themes/default/style.css');
?>

<div class="large-10 columns">
	<!-- Prepare the form -->
	<?php $form->prepare(); ?>
	<?php echo $this->form()->openTag($form); ?>
	
	<!-- Hidden form elements -->
	<?php echo $this->formRow($form->get('resourceid')); ?>
	<?php echo $this->formRow($form->get('starttimestamp')); ?>
	<?php echo $this->formRow($form->get('endtimestamp')); ?>
	
    <div class="row">
		<div class="small-7 column">
			<h4><?php echo $this->translate('New Room Booking') ?></h4>
		</div>
		<div class="small-5 column">
			<a href="#" class="button right"><i class="fa fa-undo"></i>
				Convert to pre-Booking</a>
		</div>
	</div>

	<div class="row">
		<div class="large-12 column">
			<label><?php echo $this->translate('Booking Title') ?> <small><?php echo $this->translate('required') ?></small>
    		  <?php echo $this->formRow($form->get('title'))?>
    		</label> <small class="error"><?php echo $this->translate('The title has to be between 4 and 256 characters long.') ?></small>
		</div>
	</div>

	<div class="row">
		<div class="large-6 column">
			<div class="row daterow">
				<div class="medium-8 columns">
					<label><?php echo $this->translate('Start Date') ?> <small><?php echo $this->translate('required') ?></small>
					   <?php echo $this->formRow($form->get('startdate'))?>
					</label> <small class="error"><?php echo $this->translate('Please enter the date as YYYY-MM-DD.') ?></small>
				</div>
				<div class="small-4 columns">
					<label><?php echo $this->translate('Start Time')?>
					   <?php echo $this->formRow($form->get('starttime'))?>
					</label> <small class="error"><?php echo $this->translate('Please enter the date as HH:MM.') ?></small>
				</div>
			</div>

			<div class="row daterow">
				<div class="medium-8 columns">
					<label><?php echo $this->translate('End Date') ?> <small><?php echo $this->translate('required') ?></small>
					   <?php echo $this->formRow($form->get('enddate'))?>
					</label> <small class="error"><?php echo $this->translate('Please enter the date as YYYY-MM-DD.') ?></small>
				</div>
				<div class="small-4 columns">
					<label><?php echo $this->translate('End Time')?>
					   <?php echo $this->formRow($form->get('endtime'))?>
					</label> <small class="error"><?php echo $this->translate('Please enter the date as HH:MM.') ?></small>
				</div>
			</div>
			<div class="row">
				<div class="large-12 columns">
					<label><i class="fa fa-pencil"></i> <span data-tooltip
						class="has-tip"
						title="<?php echo $this->translate('Please describe what activities you plan to carry out with the selected ressource.') ?>"><?php echo $this->translate('Booking Description') ?></span>
						<small><?php echo $this->translate('optional') ?></small> <?php echo $this->formRow($form->get('bookingdescription'))?> </label>
					<small class="error"><?php echo $this->translate('Please keep the description under 2.048 characters.') ?></small>
				</div>
			</div>
			<div class="row">
				<div class="large-12 columns">
					<label><i class="fa fa-users"></i> <span data-tooltip
						class="has-tip"
						title="<?php echo $this->translate('Please describe who will be participating in the activity planned.') ?>"><?php echo $this->translate('Participant Description') ?></span>
						<small><?php echo $this->translate('optional') ?></small> <?php echo $this->formRow($form->get('participantdescription'))?> </label>
					<small class="error"><?php echo $this->translate('Please keep the description under 2.048 characters.') ?></small>
				</div>
			</div>
			<div class="row">
				<div class="large-12 columns">
					<label><i class="fa fa-user"></i> <span data-tooltip
						class="has-tip"
						title="<?php echo $this->translate('Should you book this resource on behalf of another person you can add their details here.') ?>"><?php echo $this->translate('Person Responsible') ?></span>
						<small><?php echo $this->translate('optional') ?></small> <?php echo $this->formRow($form->get('responsibility'))?> </label>
				</div>
			</div>
			<div class="row">
				<div class="large-12 columns">
					<?php echo $this->formRow($form->get('submit'))?>
				</div>
			</div>
		</div>

		<div class="large-6 column">
			<div id="resourcetree"></div>
	   </div>
	</div>


	<!-- Close the form -->
<?php echo $this->formHidden($this->form->get('csrf')); ?>
	<?php echo $this->form()->closeTag();?>
</div>

<!-- Add/edit Specific JavaScript Components -->
<?php $this->inlineScript()->prependFile($this->basePath() . '/js/roombooking/edit.js')?>