<?php
// module/Application/view/application/resource/index.phtml:

$title = $this->translate('Hierarchy Overview');
$this->headTitle($title);
?>
<div class="large-10 columns">
    <h4><?php echo $this->translate('Hierarchy Overview'); ?></h4>
    
    <p>
        <?php echo $this->escapeHtml($this->translate('Hierarchies contain rooms and/or equipment.'));?>
        <?php echo $this->escapeHtml($this->translate('Hierarchies group these resources logically.'));?>
        <?php echo $this->escapeHtml($this->translate('They are not bookable on their own.'));?>
    </p>
    
	<table class="resources">
		<thead>
			<tr>
				<th><?php echo $this->translate('Resource ID') ?></th>
				<th><?php echo $this->translate('Description') ?></th>
			</tr>
		</thead>
		<tbody>
		 <?php if($hierarchies === null) :?>
		 <tr class="user-record-row">
              <td><?php echo $this->translate('No Resources available.') ?></td>
         </tr>
		 <?php else : ?>
         <?php foreach ($hierarchies as $hierarchy) : ?>
         <tr class="user-record-row">
              <td><a href="<?php echo $this->url('hierarchy/hierarchyEdit', array('id' => $hierarchy->geth_hierarchyid()));?>"><?php echo $hierarchy->geth_hierarchyid();?></a></td>
              <td><a href="<?php echo $this->url('hierarchy/hierarchyEdit', array('id' => $hierarchy->geth_hierarchyid()));?>"><?php echo $this->escapeHtml($hierarchy->geth_name());?></a></td>
         </tr>
         <?php endforeach; ?>
         <?php endif; ?>
        </tbody>
	</table>
</div>