<?php
    $this->headLink()->prependStylesheet($this->basePath() . '/js/fullcalendar/fullcalendar.css');
    $this->headLink()->prependStylesheet($this->basePath() . '/js/fullcalendar/fullcalendar.print.css', 'print');
?>

<div class="large-10 columns">
	<div id="calendar">
		<!-- The calender will be rendered dynamically here. -->
	</div>
	
    <div id="bookingModal" class="reveal-modal" data-reveal>
        <!-- Foundation 5 requires the modal to be in the DOM when calling $(document).foundation. So we do prepare it here. -->
        <div class="content">
            <!-- Booking content will be rendered here. -->
        </div>
        <a class="close-reveal-modal">&#215;</a>
    </div>
</div>

<!-- Calendar View Specific JavaScript Components -->
<?php $this->inlineScript()
    ->prependFile($this->basePath() . '/js/roombooking/calendar.js')
?>