<?php
    $this->headLink()->prependStylesheet($this->basePath() . '/js/fullcalendar/fullcalendar.css');
    $this->headLink()->prependStylesheet($this->basePath() . '/js/fullcalendar/fullcalendar.print.css', 'print');
?>

<div class="large-10 columns">
	<div id="calendar">
		<!-- The calender will be rendered dynamically here. -->
	</div>
	
	<!-- Foundation 5 requires the modals to be in the DOM when calling $(document).foundation. So we prepare them here. -->
    <div id="bookingModal" class="reveal-modal" data-reveal>
        <div class="content">
            <!-- Booking content will be rendered here. -->
        </div>
        <a class="close-reveal-modal">&#215;</a>
    </div>
    
    <div id="deleteModal" class="reveal-modal" data-reveal>
        <div class="content">
            <!-- Delete confirmation will be rendered here. -->
        </div>
        <a class="close-reveal-modal">&#215;</a>
    </div>
</div>

<!-- Calendar View Specific JavaScript Components -->
<?php $this->inlineScript()
    ->prependFile($this->basePath() . '/js/roombooking/calendar.js')
?>